name: linux-ci

on:
  push:
    branches: [ master ]

jobs:
  ci:
    name: run tests and check for coverage
    runs-on: ubuntu-20.04
    steps:

      - name: Git checkout
        uses: actions/checkout@v2

      - name: Java JDK 11 setup
        uses: actions/setup-java@v1.3.0
        with:
          java-version:  11
          architecture: x64

      - name: Run tests via gradle
        run: ./gradlew clean test --stacktrace