name: windows-ci

on:
  push:
    branches: [ master ]

jobs:
  ci:
    name: run tests, style verification and measure code coverage
    runs-on: windows-2019
    steps:

      - name: Git checkout
        uses: actions/checkout@v2

      - name: Java JDK 11 setup
        uses: actions/setup-java@v1.3.0
        with:
          java-version:  11
          architecture: x64

      - name: Run tests via gradle
        run: ./gradlew.bat clean test